# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765c7684c758542e10d601505e3f8294cb25935fc43317122ab83266f93b581f5ca38ae10f17ed40b4185447e6006816a03dc7855f80262993a833c224e7a2d9

test:
  secret_key_base: bfc9e59e625c91d27e87b49d61c7010f642af47c186b2647cf22eb14c926d0a83c4f727223a26c3920b3dc84d176d4521e3534aaaada4797fedb958378639e49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
